name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: trial_laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, pdo, pdo_mysql
        coverage: none

    - name: Copy .env.testing
      run: cp .env.testing .env

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Generate app key
      run: php artisan key:generate

    - name: Set Laravel APP_URL
      run: |
        sed -i 's|APP_URL=.*|APP_URL=http://localhost|' .env
        sed -i 's|DB_HOST=.*|DB_HOST=127.0.0.1|' .env
        sed -i 's|DB_DATABASE=.*|DB_DATABASE=trial_laravel|' .env
        sed -i 's|DB_USERNAME=.*|DB_USERNAME=root|' .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: |
        if [ -f ./vendor/bin/pest ]; then
          ./vendor/bin/pest
        else
          php artisan test
        fi
